### ISSUE TITLE
Aquifer Codes and Potential Interpretive Difficulties

### ISSUE THREAD

**Issue by wasquith-usgs** [scworland-usgs/restore-2018#20]
I believe these points are are regulated to accumulation in SCW's processing of the covariates. I don't full grasp the subtleties of his efforts.  I have been experimenting with the no-flow problem using categories of the aquifers attribute. Some commentary is annotated in the screenshot below.

![screen shot 2018-01-11 at 2 02 35 pm](https://user-images.githubusercontent.com/5130560/34883698-f4b6eac2-f77f-11e7-8417-088dc8c1a14f.png)

Points of order:

The High Plains aquifer (over which I live) should not be showing up in our table for it resides far off to the west and for at least the last 50 years effectively has not hydrologic connection of import for us.

The Edwards-Trinity is situated about about 800km (vertical axis) and causes the Texas Hill Country to have sustained baseflow relative to the areas outside the Edwards-Trinity outcropping. I have circled a class of rivers in south'ish Texas for which the classification does not make hydrologic sense.

It appears likely the that "other rocks" (though having a strong west east bias, which coincides with two zones [Texas and Central Florida]) might not be useful. Now that being said, if "other rocks" is to be interpreted as "Hey man, there is a missing aquifer here!", then potentially regionalization could be organized to capitalize on this as it is possible that "other rocks" do have a correlation to sites with lots of zero flow values. But if zero flow values are associated with recharge zones in Texas and Florida for which lots of water can enter, then the "other rocks" does not capture that form of hydrologic interpretation.

Concerning the Edwards aquifer, which does not appear to be a "unit" in SCW's covariates, you might be interested in this video: https://www.youtube.com/watch?v=850kNMUOEKc
that shows flood flow scalping on Seco Creek west of San Antonio. There is a strong belt of sites in our study that are dry almost all the time---I am still studying how to "know" that in a regionalization setting.

**Comment by scworland-usgs** [comment]
Should we do the same for all the immutable variables listed above? For just some of them? If just some of them, which ones? My function to download the data from SB has a "type" flag so it will be as easy as passing a vector of types to the loop that downloads the data

**Comment by wasquith-usgs** [comment]
I don't know.  But I have done extensive work with the EcoRegionsIII, they look promising, but I wonder at their quality for a large river transporting as a corridor through the EcoRegion. In Texas, we have quite strong effects of the EcoRegion---but often its coupling to geology. Limestone regions versus other.

**Comment by scworland-usgs** [comment]
I am rerunning the add_immutable_vars.R script using catchment scale for the grouping variables. I will push the new data file to github after it is completed. The only change will be the names of the groups for each grouping variable (ecoregions, soil class, physiographic region...etc) but the data format will remain the same.

**Comment by scworland-usgs** [comment]
The data file is updated. Rerun the same code that created the map at the top of this issue and see if it makes more sense.
