### ISSUE TITLE
Response variables

### ISSUE THREAD

**Issue by rrknight-usgs** [scworland-usgs/restore-2018#3]
[2003-Redundancy_and_the_choice_of_hydrologic_indices_for_characterizing_streamflow_regimes.pdf](https://github.com/scworland-usgs/restore-2018/files/1396088/2003-Redundancy_and_the_choice_of_hydrologic_indices_for_characterizing_streamflow_regimes.pdf)
Scott / Will,
I had a good talk w Stacey Archfield today (as a subpart of a discussion on trends).  I asked what she thought about identifying which characteristics of the flow regime would be most useful for estimating if there were no other guidance for a given area... which is sort of where we stand.
We collectively came up with the Olden and Poff paper (DOI below).  In short, they did a national analysis... winnowed down the number of useful characteristics based on dominant hydro process driving a river...  that may be a good start...  we can talk.
Second idea...  use the IHA metrics (~32) that are sort of commonly accepted... though the way they were intended to be used is useless....
 
doi.wiley.com/10.1002/rra.700

**Comment by scworland-usgs** [comment]
So we choose the statistics from Table 3 for each "stream type" underlined below? I think we are ok to not use the "snow and rain" stream type. That seems misclassified to me.

![image](https://user-images.githubusercontent.com/11577981/31777027-02e81a38-b4bb-11e7-8b93-332c4672a648.png)

![image](https://user-images.githubusercontent.com/11577981/31777233-9595d1b8-b4bb-11e7-93fa-639d214d8cd1.png)

**Comment by scworland-usgs** [comment]
We have decided to model daily streamflow so this issue is no longer relevant
