### ISSUE TITLE
network optimization

### ISSUE THREAD

**Issue by rrknight-usgs** [scworland-usgs/restore-2018#4]
Scott / Will,

@scworland-usgs @wasquith-usgs  --> Here is a paper on network optimization that we have been looking at in the last few months.  I think it is probably what we would call state-of-the-art on the topic.

@wasquith-usgs  --> I know you had some thoughts regarding SVMs and using the output from the model work that BB was doing... wonder if that line of thought and that presented in this paper are similar trains on parallel tracks???

I'd be interest to hear your thoughts on the topic / paper.  I had a good conversation w/Julie Kiang about this the other day.  There seems to be 2 basic ideas: (1) bring GLS-NET up-to-date or (2) do something different.   Regarding this project: Network optimization doesn't have to be done exactly simultaneous to the current model task, but should follow closely. It does seem that the modeling effort and the net opt effort can be (are???) closely linked... could it be that  is an efficient route to go?  (I have ~$810K to fund gages, and placement of those is suppose to be based on the net opt analysis.)
I appreciate you both.

Rodney

[2017-Information_theory-based_decision_support_system_for_integrated_design_of_multivariable_hydrometric_networks.pdf](https://github.com/scworland-usgs/restore-2018/files/1412499/2017-Information_theory-based_decision_support_system_for_integrated_design_of_multivariable_hydrometric_networks.pdf)

**Comment by scworland-usgs** [comment]
I will try to read this paper before the weekend and we can discuss it next week or the week after. I am interested to hear @wasquith-usgs ideas. Here are several more papers that take similar approaches:

http://www.sciencedirect.com/science/article/pii/S0022169415006630
http://onlinelibrary.wiley.com/doi/10.1029/2009WR008953/full

**Comment by wasquith-usgs** [comment]
Have had a look at the papers. Quite interesting though stretching my math talents.  What drew me to a SVM is that it clearly identifies those sites nearest to the classification/regression line and those acquire weights of zero and hence are not needed. The SVM turns a regression problem kind of around by it requiring the watersheds in most distal places in watershed property (RHS) and even the discharge (LHS) reaches of hyperspace. The SVM argues that the most unusual sites are in fact the most important ones in the network. That is my basic thinking but it is a very easily explained topic.
