### ISSUE TITLE
Water Year or Calendar Year

### ISSUE THREAD

**Issue by wasquith-usgs** [scworland-usgs/restore-2018#5]
We have talked from time to time but drawing blank. Here is an issue for permanent reference. Computations based on water year or calendar year in regards to flow statistics? Are then watershed property changes based on water year or calendar?  My akqdecay package is currently built on the "year" and not "wyear."  I choose "year" because the idea of "decade" makes more sense when the date stamp is parsed into its YYYY MM DD triad.

**Comment by scworland-usgs** [comment]
If you don't think the choice will affect our results (do you? @wasquith-usgs or @rrknight-usgs), let's just stick with calendar year so everything is consistent.

**Comment by rrknight-usgs** [comment]
I don't care either way. @scworland-usgs  Everything is consistent with what?  Climate?

**Comment by wasquith-usgs** [comment]
It is easier for writing and coding with multiple databases involved just to use calendar. Yeah we lose incomplete years on FDCs with calendar year just a bit more often than with water year but the problem remains the same. Also if we have a climate driver of anytype, NOAA NWS work on calendar don't they?

**Comment by scworland-usgs** [comment]
Let's settle on calendar year
